### ISSUE TITLE
Support goog.loadModule generation

### ISSUE THREAD

**Issue by wallw-bits** [ngageoint/opensphere-build-resolver#52]
The resolver needs to support processing files using `goog.module()` by wrapping the entire file contents in:
```
goog.loadModule(function(exports) {
    "use strict";

    … module source …

    return exports;
});
//# sourceURL=<original file>
```
(per [goog.module wiki](https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide#bundling-googmodule-files-with-other-javascript)) and subsequently placing the new output in something like `.build/module-src/same/path/and/filename.js`.

**Comment by wallw-bits** [comment]
@schmidtk I'm a bit worried about writing out N files (thousands, in our case) on every build. I think it would be better to have the resolver list out files that need to be wrapped (say in `.build/gcc-goog-modules` and then match that up with the `gcc-manifest` to do all the wraps in a single, concatenated file. The only downside is that we will likely need to do a source map for that rather than just the source URL in order for the debugger to pick it up nicely.

**Comment by schmidtk** [comment]
I've been experimenting with Closure's debug loader in `base.js` along with [`depswriter.py`](https://developers.google.com/closure/library/docs/depswriter). `depswriter.py` finds all JavaScript files in a root directory (or multiple roots) and for each file writes out a `goog.addDependency` line to register the file with Closure. They look something like this:

```
goog.addDependency('../../../../workspace/opensphere/src/os/action/eventtype.js', ['os.action.EventType'], ['goog.events.EventType'], {});
```
The args to that call are:
- The file path is relative to `google-closure-library/closure/goog`
- All `goog.provide` namespaces for that file
- All `goog.require` namespaces for that file
- The module type (empty for legacy, otherwise indicates goog/es6 modules)

I was able to load OpenSphere by generating a deps file for `opensphere`, `openlayers`, and `ol-cesium` (all Closure libs... Closure provides its own in `deps.js`) and reconfigure `index.html`'s script loading to something like this:

```
<!-- load vendor scripts resolved from index files -->
<script src=".build/gcc-defines-debug.js"></script>
<script src="/path/to/google-closure-library/closure/goog/base.js"></script>
<script src="/path/to/google-closure-library/closure/goog/deps.js"></script>
<!-- load generated deps script -->
<script>
  // this bit fixed modules not waiting for legacy dependencies to finish loading
  goog.Dependency.defer_ = true;
  goog.bootstrap([/* entry point ns */], goog.nullFunction);
</script>
```

Additionally `gcc-defines-debug.js` needed one more define to resolve a script load error in Chrome:
```
"goog.ENABLE_CHROME_APP_SAFE_SCRIPT_LOADING": true
```

To accomplish the above, we would need to:
- Modify the resolver to generate the arguments to `depswriter.py`
- Add a script to `opensphere-build-closure-helper` to run `depswriter.py`
- Remove the debug loader
- Add entry point(s) for each index file to the index options (`index.js`), `osmain` for OpenSphere
- Update index templates to reflect the above changes
- Update `opensphere-build-index` to generate the new index files accordingly

**Comment by wallw-bits** [comment]
This is finished and is largely handled in [opensphere-build-closure-helper](https://github.com/ngageoint/opensphere-build-closure-helper) and [opensphere-build-index](https://github.com/ngageoint/opensphere-build-index).
